### ISSUE TITLE
Library can no longer be built since Go 1.18

### ISSUE THREAD

**Issue by Kagetsuki** [stellitecoin/libznipfs#3]
Both the development and v2.2.0 branches fail to build under 1.18 due to incompatibility with qtls/quic-go, which appears to no longer be updated. I'd imagine fixing this would require transitioning away from quic-go to something else, or forking and updating qtls as it seems to no longer be maintained and is archived: https://github.com/marten-seemann/qtls.

**Comment by hayzamjs** [comment]
I've updated the dependencies, the CI/CD needs some work but it should be functioning now I tested on a 64-bit linux machine with the example.

Feel free to reopen issue in case you face any issue.
