### ISSUE TITLE
Missing important features

### ISSUE THREAD

**Issue by mctrivia** [stellitecoin/libznipfs#5]
Not sure if this is just a limitation of running this as a library but some important features are missing like the ability to add raw data or to pin cid so your node perpetually shares the file.

One example of raw data is cid:  `bafkreicr2pggml4j5bjv3hhxi5i5ud4rgnnaqphrfs2mtoub77zfiwbhju`
Which has the following json encoded in it:
`{"data":{"assetName":"Custom Digibyte Elf NFT #11","description":"Hair-common\n Eyes- common\n Skin- common\n Hooded cape- common\n Background- common\n\n\n","urls":[{"name":"icon","url":"ipfs://QmTBL4mArqYWbn3fEfr8yJRMqZv7e56znKFvG8zTFqMVo3","mimeType":"image/jpeg"}],"site":{"url":"https://digibyteelfsociety.digiassetx.com/","type":"web"},"issuer":"@MajesticJay218","assetId":"La8hEboypLnBHnGF6gPdZRP5QyeW2DmAdTpgXd"}}`

raw is important because it allows you to use existing sha256 hashes to find the raw added data.  Without this IPFS adds extra header data which changes the hash.

**Comment by hayzamjs** [comment]
I'll look into this "raw" data later but I've added in pin as well as another function to see pinned hashes
